// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkxU7A7XXKHH7mNX_gJXubG2ISYy5YjJY',
    appId: '1:91042370703:web:4b4dc7028a220a507d8cfa',
    messagingSenderId: '91042370703',
    projectId: 'udhaar-45f19',
    authDomain: 'udhaar-45f19.firebaseapp.com',
    storageBucket: 'udhaar-45f19.firebasestorage.app',
    measurementId: 'G-PBVZ0Z23CC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg5PhrJp2rWXLcAbEwfDbORgt5GRHAOc8',
    appId: '1:91042370703:android:286b1b217523b1e07d8cfa',
    messagingSenderId: '91042370703',
    projectId: 'udhaar-45f19',
    storageBucket: 'udhaar-45f19.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG7eBl58LArsPgJKvj-6s89yVb9b9idzY',
    appId: '1:91042370703:ios:f2028fba3d7f2d4a7d8cfa',
    messagingSenderId: '91042370703',
    projectId: 'udhaar-45f19',
    storageBucket: 'udhaar-45f19.firebasestorage.app',
    iosBundleId: 'com.example.udhaar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDG7eBl58LArsPgJKvj-6s89yVb9b9idzY',
    appId: '1:91042370703:ios:f2028fba3d7f2d4a7d8cfa',
    messagingSenderId: '91042370703',
    projectId: 'udhaar-45f19',
    storageBucket: 'udhaar-45f19.firebasestorage.app',
    iosBundleId: 'com.example.udhaar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkxU7A7XXKHH7mNX_gJXubG2ISYy5YjJY',
    appId: '1:91042370703:web:bcb46a6fad7a09957d8cfa',
    messagingSenderId: '91042370703',
    projectId: 'udhaar-45f19',
    authDomain: 'udhaar-45f19.firebaseapp.com',
    storageBucket: 'udhaar-45f19.firebasestorage.app',
    measurementId: 'G-JMQG23XMQT',
  );
}