name: Build and Deploy Flutter App

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.4'
    - name: Cleaning Flutter
      run: flutter clean
      
    - name: Install dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release

    - name: Delete Existing Releases (if any)
      uses: dev-drprasad/delete-older-releases@v0.2.1
      with:
        keep_latest: 0  # Ensure no older releases remain
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create or Update Release
      uses: ncipollo/release-action@v1
      with:
        tag: latest-apk
        name: Latest Android APK
        draft: false
        prerelease: false
        artifacts: build/app/outputs/flutter-apk/app-release.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
